name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish snapshot package
        run: mvn --batch-mode --update-snapshots clean deploy
        env:
          PACKAGES_WRITE_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up git user name
        run: git config --global user.name "GitHub Action"
      - name: Set up git user email
        run: git config --global user.email "githubaction@noreply.com"
      - name: Tag and release package
        run: mvn --batch-mode release:clean release:prepare release:perform
        env:
          PACKAGES_WRITE_PAT: ${{ secrets.GITHUB_TOKEN }}
